import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/footer";
import { Lora} from "next/font/google";
import Script from "next/script";
export const metadata = {
  title: "Blog website",
  description: "Generated by create next app",
};


const lora = Lora({
  subsets: ["latin"],
  variable: "--font-Lora",
  weight: ["600"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} `}
      >
        <Script strategy="beforeInteractive" id="show-banner">
          {`if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }`}
        </Script>

        <main className="dark:bg-dark overflow-x-hidden">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
