import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/footer";
import { Space_Grotesk, Trocchi } from "next/font/google";
import Script from "next/script";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-spaceGrotesk",
});

const trocchi = Trocchi({
  subsets: ["latin"],
  variable: "--font-Trocchi",
  weight: ["400"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${trocchi.variable} font-SpaceGrotesk`}
      >
        <Script strategy="beforeInteractive" id="show-banner">
          {`if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
            document.documentElement.classList.add('dark')
          } else {
            document.documentElement.classList.remove('dark')
          }`}
        </Script>

        <main className="dark:bg-dark overflow-x-hidden">
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
